### ISSUE TITLE
asyncio.queues.QueueFull

### ISSUE THREAD

**Issue by thetiana** [ampledata/cotproxy#7]
ERROR:
pytak INFO - Complete: <Task finished name='Task-4' coro=<RXWorker.run() done, defined at /usr/lib/python3/dist-packages/pytak/classes.py:231> exception=QueueFull()>
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-4' coro=<RXWorker.run() done, defined at /usr/lib/python3/dist-packages/pytak/classes.py:231> exception=QueueFull()>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pytak/classes.py", line 241, in run
    self.queue.put_nowait(data)
  File "/usr/lib/python3.9/asyncio/queues.py", line 151, in put_nowait
    raise QueueFull
asyncio.queues.QueueFull

OS: debian:bullseye-slim

aiohttp==3.8.1   - if this have some matter, because in my case doesn't start with the provided installation instructions

service runs inside docker container

**Comment by ampledata** [comment]
COTProxy is being retired: this repository is now archived and unsupported, so this issue is being closed. For maintained TAK tooling see https://github.com/snstac/pytak and the other snstac projects.
